### ISSUE TITLE
Concurrent session check with couchbase

### ISSUE THREAD

**Issue by vaseemahmed01** [mkopylec/session-couchbase-spring-boot-starter#10]
In Our application, we have implemented Couchbase to keep HTTP session. We have enabled concurrent user check (no.of concurrent user is configured as 1) as below. 
Added this below line into our @Configuraion class -
**http.sessionManagement().maximumSessions(1).maxSessionsPreventsLogin(true);**

if concurrent session is exceed, we are getting access error and showing error page as per expected. But we observed that session is not deleted from the Couchbase server, because of that,  even we close all the session browsers , we are not able to login the application.

So application is not allowing user to log-in and keep throwing the same error due to existing session.

And problem because of each time Couch base session creates before security check, and while error it is not deleting.

Please help us this issue to resolve.

**Comment by vaseemahmed01** [comment]
Please help on this immediate basis

**Comment by mkopylec** [comment]
Hi, I will analyze the problem but probably the problem is related to [Spring Security](https://github.com/spring-projects/spring-security)

**Comment by mkopylec** [comment]
In the [docs](http://docs.spring.io/spring-security/site/docs/3.2.6.RELEASE/apidocs/org/springframework/security/config/annotation/web/configurers/SessionManagementConfigurer.ConcurrencyControlConfigurer.html#maxSessionsPreventsLogin(boolean)) it clearly states that the session is not deleted when `maxSessionsPreventsLogin(true)`

**Comment by vaseemahmed01** [comment]
Ok i am setting false and checking it..

**Comment by vaseemahmed01** [comment]
Thanks for yor help ,
But no, we can not set the false , because it allows to login if authentication is true,  we dont need it , we want to set true to restrict the login. 
please suggest on this

**Comment by mkopylec** [comment]
I think you really should create an issue on Spring Security project and explain your problem there. This is not the case of the Session Couchbase Starter.
