### ISSUE TITLE
Align to Spring Boot 1.4

### ISSUE THREAD

**Issue by snicoll** [mkopylec/session-couchbase-spring-boot-starter#2]
Spring Boot 1.4 (M2 to be released in a couple of weeks) has couchbase support now so I was wondering how we could improve this starter (or even integrate the spring session support in Spring Boot proper). 

What do you think?

**Comment by snicoll** [comment]
See also this PR https://github.com/spring-projects/spring-boot/pull/5158

**Comment by mkopylec** [comment]
First, I would like to integrate the starter with the spring-session project.
https://github.com/spring-projects/spring-session/issues/363

Than we could add some auto configuration to spring-boot project.

Is that OK for you?

**Comment by mkopylec** [comment]
From 2.0.0 the starter depends on Spring Boot Couchbase Starter
