### ISSUE TITLE
works only for the default bucket

### ISSUE THREAD

**Issue by ShajahanEM** [mkopylec/session-couchbase-spring-boot-starter#6]
Hi, since default is hard coded in the doa class for select and update statements, it works only for default bucket. Statements : SELECT \* FROM default.data,UPDATE default USE KEYS $1 SET.  Fixed it by autowiring the SessionCouchbaseProperties and appending it to the select and update statements. we can also fix it by pass it as additional argument  instead of auto wiring the  SessionCouchbaseProperties.

**Comment by mkopylec** [comment]
Oh thanks, that's a hell of a bug!

**Comment by mkopylec** [comment]
Fixed in 2.0.0
